USE adventure_awaits_db;

ALTER TABLE stories MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT NOW();
ALTER TABLE stories MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW();

INSERT INTO stories (story_title, story_description) VALUES ('Sci-Fi', 'The post apocalyptic story of Jayna.');
INSERT INTO stories (story_title, story_description) VALUES ('Mystery', 'The story of Peter the teen detective.');
INSERT INTO stories (story_title, story_description) VALUES ('Vampires', 'The story of 4 middle school vampires. Two boys, Cody and Calvin and two girls, Ivy and Ryan');
INSERT INTO stories (story_title, story_description) VALUES ('Adventure', 'The story of Travis the pocket sized kid.');

ALTER TABLE pages MODIFY COLUMN createdAt DATETIME NOT NULL DEFAULT NOW();
ALTER TABLE pages MODIFY COLUMN updatedAt DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW();

INSERT INTO pages (page_text, page_choice1, page_choice_text1, page_choice2, page_choice_text2, story_id, page_parent_id) VALUES ('Jayna awoke with a start. Outside her window, the sirens were going off again. The blaring, high pitched sirens were a warning of attack that she knew all too well. Scrambling out of bed, she ran into her mother’s room and tried to shake her awake. As usual, her mother was under the influence of her calming medication and would not wake up. “Wake up!,” Jayna yelled. Outside, she could hear the sounds of missiles slamming into the ground and exploding with a force that violently shook the house.\n\nThe current situation resulted from the third World War back in 2019. The political climate at the time was tense; nationalism and xenophobia caused the country to contract in on itself. One by one, the rest of the world followed suit; no longer were we one world. Small squabbles that would have been previously been addressed through diplomacy were now the start of small intra-country wars. Those wars grew and sides were chosen. The wars raged on. Nuclear weapons became the weapon of choice when all else failed. The last nuclear attack in 2075 was the worst. Three-quarters of the land mass on Earth became uninhabitable. The land that was left was unable to support farming of any kind. The seas turned black; the Earth’s water became undrinkable. The humans that were left had to adapt to the squalid, unlivable conditions. Communities began to spring up, but sadly, the ill will of the past flourished with it. And with it, new wars began…\n\nWhat happens next?
', 0, 'Jayna wakes her mom and they run out of the house', 0, 'Jayna cannot wake her mom up', 1, 0);
INSERT INTO pages (page_text, page_choice1, page_choice_text1, page_choice2, page_choice_text2, story_id, page_parent_id) VALUES ('We knew from the start/Things fall apart/Intentions shatter.\n\nPeter picked up the paper stuck half underneath his locker and read the words. That’s odd, he thought. Thinking nothing of it, he shoved the paper into his pocket and went to first period. He plopped violently into his chair and dropped his bag with a thud onto the floor. Where’s Henry? His best friend was always here before he was. Henry took the bus from Brooklyn and was usually at school an hour before it began. By the time Peter got to school, Henry had already eaten breakfast and was working on the homework he should have completed last night. Peter fired off a quick text, “Where you at?”, and waited for his phone to ping. Peter then pulled the piece of paper out of his pocket and read it over again. He recognized the words as lyrics to a song by the Roots. On the back of the paper was scribbled one word “help.” Dread washed over Peter. The handwriting looked awfully familiar, but not so much that he could identify it. Just then, his phone pinged. It was Henry…\n\nWhat was the message?', 0, 'Help me', 0,'I’m outside the school. Get out here.', 2, 0);
INSERT INTO pages (page_text, page_choice1, page_choice_text1, page_choice2, page_choice_text2, story_id, page_parent_id) VALUES ('They always sat at the lunch table in the back. They always kept to themselves. “They” were Washington Middle School’s weird kids. Some folks thought they were related and some folks thought they were just a random band of lost souls, but no one knew for sure because they didn’t talk to the other kids. There were four of them – two boys and two girls. The boys were named Cody and Calvin and the girls were named Ivy and Ryan. Cody was in the 8th grade and was the leader of the pack. He was tall and had short black hair that was in need of a cut. Cody was quick with his mouth and could often be seen getting frustrated with Calvin for following him around. Calvin was in the 6th grade and followed Cody around like a puppy dog. Shorter in stature and kinder in heart than Cody, Calvin was the brain of the group. He somehow earned A’s in class despite refusing to participate in class activities. Calvin told Mrs. Goldberg that when people broke off into groups, it meant that sides were being chosen and the end was coming. He didn’t elaborate as to the end of what, specifically, but he didn’t want to be responsible for the end of anything, so he wasn’t working in a group. And then there were the girls…Ivy was in the 8th grade, but only because she was held back last year. She was tall and lanky with jet black hair and crystal blue eyes. Ivy always looked suspicious as if she was expecting a monster to be hiding around every corner. Lastly, there was Ryan. Ryan was the oddball of the group. She had short, silver blonde hair and the same crystal blue eyes as Ivy, but that’s where the similarities stopped. Ryan was average in height with a cherubic face and thicker stature than Ivy. The artist of the group, Ryan preferred to spend her time in the Art room where she was often found dabbling in paints or charcoal. \n\nThis particular day, Ryan was in the Art room working on a charcoal drawing when Ivy came scrambling into the room. “Ryan,” Ivy cried, half out of breath and appearing as if she had finally run into that monster. Startled, Ryan looked up. Oh no, Ryan thought, it’s happening again…\n\nWhat is happening again?', 0, 'Cody got into a fight with another student in the cafeteria and, in a fit of rage, began to transform into a vampire', 0,'Calvin disappeared', 3, 0);
INSERT INTO pages (page_text, page_choice1, page_choice_text1, page_choice2, page_choice_text2, story_id, page_parent_id) VALUES ('James and Travis couldn’t wait for the fair. Every fall it came and was the highlight of the town’s social calendar. Friday night was the night that all of the school kids came out. They met at the big tent that was always set up in the middle of the fair. From there, they would group up and disperse into the crowd. Some kids liked to play games of chance and others wanted to hit the rides first. Josh and Billy liked to check out the arcade games that were always set up in the back. After greeting their friends, dividing up, and making a plan to meet up later for food, James and Travis ran off to the arcade. They played skee-ball and PacMan and all the other classic arcade games that were a once-a-year treat, but they left the fortune teller for last. Every year, she sat in the back of the arcade giving out readings for $5. She told folks about their futures, their troubles, and what riches were in store for them. James always saved $5 just for this; Travis always skipped it. This year was different, though. After much nudging and convincing, Travis begrudgingly agreed to let the fortune teller read his fortune. During his reading, the fortune teller told Travis that he was going on a special adventure. It was an adventure that he would never forget and would change the course of his life. Travis scoffed at the idea. That was $5 I’ll never get back, he thought. James and Travis finished out the night with their friends and headed home. In the morning, when Travis woke up, he felt strange. He opened his eyes and everything around him was large…really large. Wait. He was sleeping on his pillow! He crawled to the edge of his pillow, careful not to slide off, and looked over. His normally short jump to the floor was now a very long drop to the floor. Travis slid down his pillow onto his mattress and then down to the floor before he…\n\nWhat did Travis do?', 0, 'Realized he was going to need help and yelled for his mom', 0, 'Explored his room from a new perspective', 4, 0);
